name: Kotlin-Dagger2

on:
  push:
    paths:
      - 'Kotlin-Dagger2/**'
      - '.github/workflows/kotlin-dagger2.yml'
  pull_request:
    paths:
      - 'Kotlin-Dagger2/**'
      - '.github/workflows/kotlin-dagger2.yml'

jobs:

  matrix_build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        java-version: [ 1.8, 11, 16 ]
    name: Java ${{ matrix.java-version }} Build on ${{ matrix.operating-system }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('Kotlin-Dagger2/**/*.gradle*', 'Kotlin-Dagger2/**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build and test
      working-directory: Kotlin-Dagger2
      run: ./gradlew clean test shadowJar -i --warning-mode all

    - name: Run the package
      working-directory: Kotlin-Dagger2
      run: java -jar build/libs/lcd-numbers-di-framework-kata-1.0.0-SNAPSHOT-all.jar 12345 3

    - name: Run the package using build tool
      working-directory: Kotlin-Dagger2
      run: ./gradlew run --args="67890 3"
